apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-config
  labels:
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
{{ tpl .Values.mosquittoConfig.mosquittoConf . | nindent 4 }}