apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}
  labels:
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
  annotations:
    {{- $secretName := default (printf "%s-auth" (include "mqtt-cilium.fullname" .)) .Values.mosquittoSecrets.existingSecret }}
    secret.reloader.stakater.com/reload: {{ $secretName | quote }}
spec:
  replicas: {{ .Values.mosquittoDeployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "mqtt-cilium.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "mqtt-cilium.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml (default (dict "fsGroup" 1883) .Values.mosquittoDeployment.podSecurityContext) | nindent 8 }}
      initContainers:
        - name: init-permissions
          image: "{{ .Values.mosquittoDeployment.initPermissions.image.repository | default "busybox" }}:{{ .Values.mosquittoDeployment.initPermissions.image.tag | default "latest" }}"
          command: ["sh", "-c", "chown -R 1883:1883 /mosquitto/data"]
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto/data
      containers:
        - name: mosquitto
          image: "{{ .Values.mosquittoDeployment.image.repository }}:{{ .Values.mosquittoDeployment.image.tag }}"
          imagePullPolicy: {{ .Values.mosquittoDeployment.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: mqtt-tcp
              containerPort: 1883
            - name: mqtt-ws
              containerPort: 9001
          resources:
            {{- toYaml .Values.mosquittoDeployment.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-auth
              mountPath: /mosquitto/config/password.txt
              subPath: password.txt
            - name: mosquitto-data
              mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-config
          configMap:
            name: {{ include "mqtt-cilium.fullname" . }}-config
        - name: mosquitto-auth
          secret:
            secretName: {{ $secretName }}
            items:
              - key: password.txt
                path: password.txt
            defaultMode: 0600
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: {{ include "mqtt-cilium.fullname" . }}-data
