apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-mosquitto-config
  labels:
  {{- include "mqtt-cilium.labels" . | nindent 4 }}
data:
  mosquitto.conf: {{ .Values.mosquittoConfig.mosquittoConf | toYaml | indent 1 }}
