apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-lb
  annotations:
    cilium.io/assign-internal-ip: {{ .Values.cilium.assignInternalIP | default "true" | quote }}
    cilium.io/lb-ipam-pool-name: {{ .Values.cilium.poolName | default "default-pool" | quote }}
    lbipam.cilium.io/ips: {{ .Values.cilium.ips | quote }}
    lbipam.cilium.io/sharing-key: {{ .Values.cilium.sharingKey | default "mqtt" | quote }}
spec:
  type: LoadBalancer
  selector:
    {{- include "mqtt-cilium.selectorLabels" . | nindent 4 }}
  ports:
    - name: mqtt-tcp
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: mqtt-ws
      port: 9001
      targetPort: 9001
      protocol: TCP