apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-lb
  labels:
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
  annotations:
# Use the 'index' function to safely access keys with hyphens or dots
    cilium.io/assign-internal-ip: {{ index .Values.cilium "assign-internal-ip" | quote }}
    cilium.io/lb-ipam-pool-name: {{ index .Values.cilium "pool-name" | quote }}
    lbipam.cilium.io/ips: {{ .Values.cilium.ips | quote }}
    lbipam.cilium.io/sharing-key: {{ index .Values.cilium "sharing-key" | quote }}
spec:
  type: {{ .Values.mqttLb.type | default "LoadBalancer" }}
  selector:
    {{- include "mqtt-cilium.selectorLabels" . | nindent 4 }}
  ports:
    - name: mqtt-tcp
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: mqtt-ws
      port: 9001
      targetPort: 9001
      protocol: TCP
