apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-lb
  labels:
    homelab.service: mqtt
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
  annotations:
    # Use 'quote' and 'default' to ensure it's always a string "true" or "false"
    cilium.io/assign-internal-ip: {{ .Values.cilium.assignInternalIP | default "true" | quote }}
    cilium.io/lb-ipam-pool-name: {{ .Values.cilium.poolName | default "default-pool" | quote }}
    lbipam.cilium.io/ips: {{ .Values.cilium.ips | quote }}
    lbipam.cilium.io/sharing-key: {{ .Values.cilium.sharingKey | default "mqtt" | quote }}
spec:
  type: {{ .Values.mqttLb.type | default "LoadBalancer" }}
  selector:
    {{- include "mqtt-cilium.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.mqttLb.ports | toYaml | nindent 4 }}