apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-lb
  labels:
    homelab.service: mqtt
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
  annotations:
    cilium.io/assign-internal-ip: {{ .Values.cilium.assignInternalIp | quote }}
    cilium.io/lb-ipam-pool-name: {{ .Values.cilium.poolName | quote }}
    lbipam.cilium.io/ips: {{ .Values.cilium.ips | quote }}
    lbipam.cilium.io/sharing-key: {{ .Values.cilium.sharingKey | quote }}
spec:
  type: {{ .Values.mqttLb.type | default "LoadBalancer" }}
  selector:
    {{- include "mqtt-cilium.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.mqttLb.ports | toYaml | nindent 4 }}