apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-lb
  labels:
    homelab.service: mqtt
  {{- include "mqtt-cilium.labels" . | nindent 4 }}
  annotations:
    cilium.io/assign-internal-ip:  {{ include "cilium.assignInternalIp" . }}
    cilium.io/lb-ipam-pool-name:  {{ include "cilium.poolName" . }}
    lbipam.cilium.io/ips: {{ include "cilium.ips" . }}
    lbipam.cilium.io/sharing-key:  {{ include "cilium.sharingKey" . }}
spec:
  type: {{ .Values.mqttLb.type }}
  selector:
    app: mosquitto
    {{- include "mqtt-cilium.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mqttLb.ports | toYaml | nindent 2 }}
