apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-data
  labels:
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest | default "1Gi" }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}