{{- if .Values.mosquittoSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-cilium.fullname" . }}-auth
  labels:
    {{- include "mqtt-cilium.labels" . | nindent 4 }}
type: Opaque
data:
  password_file: {{ .Values.mosquittoSecrets.passwordData | b64enc | quote }}
{{- end }}